dist: bionic
# 18.04

language: cpp
compiler: gcc

git:
  submodules: false

addons:
  apt:
    packages:
      - xorg-dev
      - libglu1-mesa-dev
      - libompl-dev

# Hack for ssh submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

# install:
#

script:
  - ./build.sh

#after_success:
# todo: coverage