dist: bionic
# 18.04

language: cpp
compiler: gcc
sudo: required

git:
  submodules: false

addons:
  apt:
    packages:
      - xorg-dev
      - libglu1-mesa-dev

# Hack for ssh submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - wget https://ompl.kavrakilab.org/install-ompl-ubuntu.sh
  - chmod u+x install-ompl-ubuntu.sh
  - sudo ./install-ompl-ubuntu.sh
  - sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen

script:
  - ./build.sh --clean --testing

after_success:
  - ./build/grstaps_tests

#after_success:
# todo: coverage